@startuml Package

package "Domain" #DDDDDD {
  [User] 
  [Email] 
  [DomainError] 
}

package "Application" #BBCCEE {
  [CreateUserUseCase] 
  [UserDTO] 
}

package "Interfaces" #AABBCC { 
  [UserRepository] 
   }

package "Infrastructure" #99AABB { 
  package "Controllers" { 
    [UserController]  
    } 
  package "Repositories" {
     [SQLAlchemyUserRepository]  
     } 
  package "Databases" { 
    [UserModel] 
    [Database]
    }
}

Infrastructure .down.> Interfaces
Infrastructure .down.> Application

Application <.up.> Interfaces
Application <.down.> Domain

@enduml